
var tipuesearch = {"pages": [
     {"title": "Home", "text": "Welcome to the Office of Biostatistics and Quantitative Health Sciences at the University of Hawaii's John A. Burns School of Medicine" , "tags": "BQHS, Biostatistics, Quantitative Health Sciences, Hawaii, University of Hawaii, John A. Burns School of Medicine", "url": "../index.html"},
     {"title": "About Us", "text": "The faculty and staff at BQHS provides prompt, high quality biostatistical and bioinformatical services.", "tags": "About, Biostatistics & Quantitative Health Sciences, BQHS", "url": "../Home/about.html"},
     {"title": "Expertise", "text": "BQHS offers biostatistical and bioinformatical collaborations and services to promote excellence in quantitative health research. ", "tags": "expertise, bioinformatics, biostatistics, services, research, about", "url": "../Home/expertise.html"},     
     {"title": "Research Design", "text": "A strong research design is critical for clinical and translational, and basic science reseach.", "tags": "research, expertise, about", "url": "../Home/researchdesign.html"},
     {"title": "Database Development & Management", "text": "Database Development & Management involves the use of information technology interventions for clinical and translational research projects.", "tags": "database, biomedical informatics, informatics, design, development, expertise, about", "url": "../biomedinfo.html"},
     {"title": "Data Analysis", "text": "BQHS faculty and staff provide comprehensive biostatistical and bioinformatical data analysis support and services.", "tags": "data analysis, biostatistics, bioinformatics, expertise, about", "url": "../Home/dataanalysis.html"},
     {"title": "Results Dissemination", "text": "BQHS faculty and staff have extensive experience with results presentation and dissemination.", "tags": "results dissemination, results presentation, expertise, about", "url": "../Home/resultsdissem.html"},
     {"title": "Training & Education", "text": "Our experienced faculty and staff provides workshops, trainings, and courses.", "tags": "training and education, workshops, seminars, courses, credits, expertise, about", "url": "../Home/traininged.html"},
     {"title": "Faculty & Staff", "text": "Directory of Faculty and Staff at the Office of Biostatistics and Quantitative Health Sciences.", "tags": "Hyeong Jun Ahn, John J. Chen, James Davis, Eunjung Lim, Rosa Castro, So Yung Choi, Jason Delos Reyes, Rui Fang, Krupa Gandhi, Phoebe Hwang, Vedbar Khadka, Jewellien Robinson, Yang Rui, Chathura Siriwardhana, Lu Wang, people, members, faculty, staff", "url": "../Home/members.html"},     
     {"title": "Contact Us", "text": "Questions or Service Requests?  Contact us Today!", "tags": "contact, request form, contact form, new to BQHS, about", "url": "../Home/contact.html"},
     {"title": "Job Opportunities", "text": "Look for exciting opportunities in paradise?  Want to work in Biostatistics, Bioinformatics, or Database Management?  We're looking for you!", "tags": "jobs, career, positions, work, about", "url": "../Home/jobs.html"},
     {"title": "Give a Gift", "text": "Your generous gift will allow BQHS to maintain and further develop this important JABSOM infrastructure resource.", "tags": "gift, donate, money, fund, about", "url": "../Home/donate.html"},
	 {"title": "Research", "text": "BQHS is a leading center of excellence for development and application of quantitative methodology across biological, health and medical sciences, and has collaborative partnerships with various research groups in Hawaii.", "tags": "Research", "url": "../Research/research.html"},
	 {"title": "Healthcare Databases", "text": "Large healthcare databases are useful resources for clinical and translational researchers and community-based researchers. The databases, if utilized properly, can be a low-cost alternative in generating preliminary data, developing research hypothesis, or for training and educational purposes.", "tags": "healthcare databases, database, research, brfss, cms, hhic, hrs, meps, nhanes, nhis", "url": "../Research/healthcaredatabases.html"},
	 {"title": "Behavioral Risk Factor Surveillance Survey (BRFSS)", "text": "BRFSS is a cross-sectional health-related telephone (landline and cellular) survey that collects state data about U.S. residents regarding their health-related risk behaviors, chronic health conditions, and use of preventive services.", "tags": "brfss, healthcare databases, research", "url": "../Research/brfss.html"},
	 {"title": "Centers for Medicare & Medicaid Services (CMS)", "text": "CMS is a part of the Department of Health and Human Services (HHS). Medicare is a national social insurance program, providing health insurance for Americans aged 65 and older who have worked and paid into the system or younger people with disabilities, end stage renal disease and sclerosis. Medicaid is a social health care program for persons of all ages whose income and resources are insufficient to pay for healthcare.", "tags": "cms, medicare, medicaid, healthcare databases, research", "url": "../Research/cms.html"},
	 {"title": "Hawaii Health Information Corporation (HHIC)", "text": "HHIC is a non-profit corporation established in 1994 to collect healthcare data from all acute care hospitals in Hawaii, analyze and disseminate statewide health information in support of efforts to continuously improve the quality and cost-efficiency of healthcare services provided to the people of Hawaii.", "tags": "hhic, healthcare databases, research", "url": "../Research/hhic.html"},
	// {"title": "Health and Retirement Study (HRS)", "text": "HRS is a longitudinal panel study that surveys a representative sample of approximately 20,000 people in America over the age of 50 every two years. Supported by the National Institute on Aging and the Social Security Administration, HRS explores the changes in labor force participation and the health transitions that individuals undergo toward the end of their work lives and in the years that follow.", "tags": "hrs, retirement, healthcare databases, research", "url": "../Research/hrs.html"},
	// {"title": "Medical Expenditure Panel Survey (MEPS)", "text": "MEPS, administered by the Agency for Health Research and Quality (AHRQ), is a set of large scale surveys of families and individuals, their medical providers (physicians, hospitals, pharmacies, etc.), and employers across the U.S. MEPS collects data on the specific health services that Americans use such as how frequently they use them, the cost of these services, and how they are paid for, as well as data on the cost, scope, and breath of health insurance held by and available to U.S. workers.", "tags": "meps, healthcare databases, research", "url": "../Research/meps.html"},
	 {"title": "National Health and Nutrition Examination Survey (NHANES)", "text": "NHANES is a survey research program conducted by National Centers for Health Statistics (NCHS), designed to assess health and nutritional status of adults and children in the United States.", "tags": "nhanes, healthcare databases, research", "url": "../Research/nhanes.html"},
	 {"title": "National Health Interview Survey (NHIS)", "text": "NHIS is an annual, cross-sectional household interview survey program designed to monitor trends in illness and disability, to track progress toward achieving national health objectives, for epidemiologic and policy analysis by public health research community, for determining barriers to accessing using appropriate health care and evaluating federal health programs.", "tags": "nhis, interview, healthcare databases, research", "url": "../Research/nhis.html"},
	 {"title": "Collaborative Research", "text": "Our faculty and staff have experience working with collaborative research projects and welcome the development of new collaborations.", "tags": "collaborative research, research, jabsom, john a. burns school of medicine, medicine, obgyn, center for native pacific health disparities research, magnetic resonance imaging center, university of hawaii at manoa, school of nursing and dental hygiene, college of tropical agriculture and human resources, queen's medical center, shriners hospitals for children, hhic, hawaii journal of medicine and public health", "url": "../Research/collabresearch.html"},
	 {"title": "Education", "text": "Our experienced faculty and staff at BQHS provide the quantitative health sciences training and education to include workshops and seminars for trainees (graduate students, residents, fellows), faculty, and staff and for-credit biostatistics and bioinformatics courses of various levels of difficulty.", "tags": "education, courses", "url": "../Education/education.html"},
	 {"title": "Courses Offered", "text": "BQHS offers two graduate-level courses every year under the Department of Tropical Medicine, Medical Microbiology and Pharmacology", "tags": "courses, education, trmd 655, biostatistics, trmd 705, bioinformatics", "url": "../Education/coursesoffered.html"},
	 {"title": "Training", "text": "BQHS faculty and staff have provided over 40 seminars and workshops to over 11 departments/institutes in the past five years with a variety of statistical topics ranging from basic biostatistics to clinical and translational research using big data and research design to bioethics in statistics.", "tags": "training, seminar, education", "url": "../Education/training.html"},
	 {"title": "Resources", "text": " Compiled is a list of biostatistics and bioinformatics online resources for your convenience.", "tags": "resources, biostatistics resources, bioinformatics resources, courses, statistical test, calculators, software, data repositories, tools", "url": "../Education/resources.html"},
	 {"title": "Support & Services", "text": "BQHS support and services include infrastructure grant support, consultations, short-term project services, and research design and analysis plans for grant proposal development.", "tags": "support & services, support, services, infrastructure grant support, consultations, projects, grants development, service rates, request form", "url": "../Services/support.html"},
	 {"title": "Infrastructure Grant Support", "text": "BQHS serves as the quantitative health sciences specialized cores to several UH and JABSOM infrastructure grants.", "tags": "rmatrix, rmatrix-II, U54MD007584, inbre, inbre-III, P20GM103466, bridges, G12MD007601, mountain west, mountain west ctr-in, U54GM104944, center for native and pacific health disparities research, cnphdr", "url": "../Services/igrants.html"},
	 {"title": "Collaboration & Support", "text": "Services that BQHS provides include Consulations & Fee-for-Service Projects and Grant Proposal Development", "tags": "consultations, projects, grants development", "url": "../Services/services.html"},
	 {"title": "Service Rates", "text": "The current BQHS fee-for-service rates for UH or UH-affiliated projects and non-UH clients.", "tags": "rates, fee, charge, money, cost, service, pay", "url": "../Services/rates.html"},
	 {"title": "Service Request Form", "text": "To request our quantitative health sciences support, please complete and submit the BQHS Collaboration and Support Request Form", "tags": "request form, collaboration, contact", "url": "../Services/requestform.html"},
	 {"title": "Sitemap", "text": "Map of all everything on the BQHS website.", "tags": "", "url": "../Home/sitemap.html"}
]};



